name: Build

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner'
        required: true
        type: string
        default: 'self-hosted' # ubuntu-latest

jobs:
  build:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.runner || 'self-hosted' }}
    steps:
      - uses: actions/checkout@v5
      # -----------------------------
      # FREE DISK SPACE (CRITICAL)
      # -----------------------------
      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/share/powershell
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          df -h
      - name: Set ENV
        run: | 
          chmod +x *.sh
          echo "VERSION=$(date '+%Y.%m.%d')" >> $GITHUB_ENV
    
      - name: Build
        env:
            DEBIAN_FRONTEND: noninteractive
        run: |
          ./build.sh

      - name: Set
        run: |
          echo "ZIP=$(find android/lineage/out/target/product/virtio_x86_64/ -name *.iso)" >> $GITHUB_ENV
          echo "BOOT=$(find android/lineage/out/target/product/virtio_x86_64/boot.img)" >> $GITHUB_ENV
          echo "RECOVERY=$(find android/lineage/out/target/product/virtio_x86_64/recovery.img)" >> $GITHUB_ENV

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            recovery-userdebug.img
            ${{ env.ZIP }}
            ${{ env.BOOT }}
            ${{ env.RECOVERY }}
